00-CommeChezSwa/WebApp/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Drawing.Text;
using WebApp.Data;
using WebApp.Models;
using WebApp.Repositories;

namespace WebApp.Controllers
{
    public class MenuController : Controller
    {
        //private MenuRepository _menuRepo = new MenuRepository();

        private readonly MenuRepository _menuRepo;

        public MenuController()
        {
            _menuRepo = new MenuRepository();
        }

        public IActionResult Index(string id)
        {
            MenuViewModel menuModel = new()
            {
                Menu = _menuRepo.GetById(id),
                Menus = _menuRepo.GetAll().ToList()
            };
            return View(menuModel);
        } 
    }
}

00-CommeChezSwa/WebApp/Controllers/ReservatieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using WebApp.Data;
using WebApp.Models;
using WebApp.Repositories;


namespace WebApp.Controllers
{
    public class ReservatieController : Controller
    {
        public IActionResult Index()
        {
            IEnumerable<Reservatie> reservaties = ReservatieRepository.GetAll();
            return View(reservaties);
        }

    
        public IActionResult Create()
        {
            ReservatieViewModel model = new ReservatieViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ReservatieViewModel model)
        {
            if (ModelState.IsValid)
            {
                Reservatie reservatie = new Reservatie
                {
                    Voornaam = model.Voornaam,
                    Familienaam = model.Familienaam,
                    Email = model.Email,
                    Tijdslot = model.Tijdslot,
                    AantalPersonen = model.AantalPersonen,
                    DatumReservatie = model.DatumReservatie
                };
                ReservatieRepository.Add(reservatie);

                //Add to repository
                return RedirectToAction(nameof(Success));
            }
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            Reservatie reservatie = ReservatieRepository.GetById(id);
            return View(reservatie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Reservatie reservatie)
        {
            if (ModelState.IsValid)
            {
                ReservatieRepository.Update(reservatie);
                return RedirectToAction("Details", new { id = reservatie.ReservatieID });
            }

            return View(reservatie);
        }


        public IActionResult Details(int id)
        {
            Reservatie reservatie = ReservatieRepository.GetById(id);
            return View(reservatie);
        }

        //public IActionResult Delete(int id)
        //{
        //    Reservatie toDelete = ReservatieRepository.GetById(id);
        //    return View(toDelete);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id) /* extra parameter nodig voor overload */
        {
            Reservatie toDelete = ReservatieRepository.GetById(id);
            ReservatieRepository.Delete(toDelete);

            return RedirectToAction("Index");
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

00-CommeChezSwa/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="~/img/logo_comme_chez_swa.png" width="100" height="100" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">Over Ons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index" asp-route-Id="LUNCH">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservatie" asp-action="Create">Reservatie Maken</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>